### ISSUE TITLE
Fix for borrow error discussed on IRC

### ISSUE THREAD

**Issue by smarnach** [fubarnetes/overlord#2]
For what it's worth, I just gave the issue we discussed yesterday a quick look again.

It's possible to resolve the issue by [storing the dereferenced `MutexGuard` in an intermediary variable](https://play.rust-lang.org/?gist=f2891d73db864bcfc5c55fdb8604c4b4&version=stable), while the [code without that intermediary variable fails to compile](https://play.rust-lang.org/?gist=083d88674eab7a3cd120943d09aa5cab&version=stable).

**Comment by smarnach** [comment]
After some discussion on StackOverflow, I understood why this is happening.  The borrow checker only uses the information in function _signatures_ to track borrows.  The signature of `deref_mut()` for `MutexGuard` is 

    fn deref_mut(&mut self) -> &mut T

where `T` is the wrapped type (i.e. `_Process`).  From this signature, all the borrow checker can infer is that the returned `T` has a lifetime linked to the `MutexGuard` that was passed in.  What exactly the relation between the two is does not follow from the signature, so the borrow checker needs to mark the whole `MutexGuard` object as borrowed mutably.

**Comment by fabianfreyer** [comment]
Thanks for the followup! This is extremely helpful.
